### ISSUE TITLE
just to say that this project is awesome

### ISSUE THREAD

**Issue by actuallyabhi** [raggesilver/proton#1]
Hi sir!. i am new to vala and i was roaming around to see few projects and i got this . Trust me your project is awesome and i will love contribute to this.
+1

**Comment by raggesilver** [comment]
Thanks! Proton is currently being rewritten so it's a good time to get to know the code base. Just a reminder that this project is hosted at https://gitlab.com/raggesilver-proton/proton and this is the rewrite branch https://gitlab.com/raggesilver-proton/proton/-/tree/proton2.

If you're new to Vala I highly recommend you follow Vala on Twitter https://twitter.com/vala_lang. Anything you need is probably documented at https://valadoc.org
