### ISSUE TITLE
Dependencies from "gobject-introspection".

### ISSUE THREAD

**Issue by kotler-dev** [raggesilver/proton#2]
When I installed Proton in Manjaro Gnome (AUR), it gave me a bug: "src/meson.build:37:0: ERROR: Program 'g-ir-compiler' not found".

I found out that "gobject-introspection" need tobe installed. Before in my system i had "gobject-introspection-runtime".

Maybe "Dependencies" needs "gobject-introspection" to be added?

P.S. How can I help you? I'm newcomer in Vala, but i want to be helpful.
Telegram @hyperhunt

**Comment by raggesilver** [comment]
So, this kind of problem is one of the reasons I chose to ship Proton via Flatpak. I used Manjaro briefly this year but never ended up trying to install Proton natively. I've spoken to the maintainer of AUR Proton a couple of times, he's very considerate I'm sure if you comment on the AUR page he'll try and fix that.

> How can I help you? I'm newcomer in Vala, but i want to be helpful.

Thanks for the interest in helping develop Proton. I've been super busy with my full time job to work on Proton for these few past months so development is kind of inactive. First thing I'd suggest would be to go to Proton's actual repo https://gitlab.com/raggesilver-proton/proton.

I DM'd you a link to a Vala Telegram group -- they may assist you if you ever get stuck with something. Also, https://valadoc.org, always refer to that first.

**Comment by kotler-dev** [comment]
Thanks for you answer. I added comment on the AUR page.
